stages:
  - build

variables:
  CMAKE_BUILD_TYPE: "Release"
  VCPKG_ROOT: "$CI_PROJECT_DIR/vcpkg"
  TZ: "Europe/Rome"

cache:
  key: vcpkg-cache
  paths:
    - "$CI_PROJECT_DIR/vcpkg"
    - build/vcpkg_installed

before_script:
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  - apt-get update
  - apt-get install -y --no-install-recommends apt-utils ca-certificates git cmake unzip tar build-essential flex zip curl bison pkg-config python3 python3-setuptools python3-jinja2 autoconf automake libtool libltdl-dev '^libxcb.*-dev' libx11-xcb-dev libgl1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libxtst-dev
  - git submodule update --init --recursive
  - if [ ! -d "$VCPKG_ROOT" ]; then git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT; fi
  - $VCPKG_ROOT/bootstrap-vcpkg.sh
  - export PATH="$VCPKG_ROOT:$PATH"

.build_and_test_template: &build_and_test_template
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..
    - cmake --build .
    - ./ddbtest

build_and_test_ubuntu_20_04:
  stage: build
  image: ubuntu:20.04
  <<: *build_and_test_template

build_and_test_ubuntu_22_04:
  stage: build
  image: ubuntu:22.04
  <<: *build_and_test_template

build_and_test_ubuntu_24_04:
  stage: build
  image: ubuntu:24.04
  <<: *build_and_test_template
