FROM ubuntu:focal
MAINTAINER Adam Steer <adam.d.steer@gmail.com>

RUN apt update && apt install  -y --fix-missing --no-install-recommends\
    build-essential \
    ca-certificates \
    cmake \
    git \
    libboost-all-dev

RUN apt install -y sqlite3 spatialite-bin geographiclib-tools exiv2 cmake geos libgeos-dev gcc-8 gdal libgdal-dev

RUN git clone https://github.com/uav4geo/DroneDB.git && \
    cd DroneDB && \
    mkdir build && \
    cd build && \
    cmake .. && make
