FROM ubuntu:20.04

# Define environment variables
ENV CMAKE_BUILD_TYPE=Release \
    VCPKG_ROOT=/vcpkg \
    TZ=Europe/Rome

# Set the timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install required dependencies
RUN apt-get update && apt-get install -y apt-utils git cmake unzip tar build-essential flex zip curl bison pkg-config python3 python3-jinja2 autoconf automake libtool pkg-config '^libxcb.*-dev' libx11-xcb-dev libgl1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libxtst-dev && rm -rf /var/lib/apt/lists/*

# Make /vcpkg a volume
VOLUME /vcpkg

# Clone and bootstrap vcpkg if not already cloned
RUN if [ ! -d "$VCPKG_ROOT/.git" ]; then \
        git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT && \
        $VCPKG_ROOT/bootstrap-vcpkg.sh; \
    fi && \
    echo "export PATH=\"$VCPKG_ROOT:$PATH\"" >> /etc/profile

# Set the PATH for vcpkg
ENV PATH="$VCPKG_ROOT:$PATH"

# Define the default working directory
WORKDIR /workspace