FROM ubuntu:24.04

# Define environment variables
ENV CMAKE_BUILD_TYPE=Release \
    VCPKG_ROOT=/vcpkg \
    TZ=Europe/Rome \
    PYENV_ROOT=/root/.pyenv \
    PATH=/root/.pyenv/bin:/root/.pyenv/shims:/root/.pyenv/versions/bin:$PATH

# Set the timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install required dependencies
RUN apt-get update && apt-get install -y \
    apt-utils git cmake unzip tar build-essential flex zip curl \
    bison pkg-config python3 python3-jinja2 python3-setuptools autoconf automake libtool \
    libreadline-dev libssl-dev lbzip2 libbz2-dev zlib1g-dev libffi-dev liblzma-dev \
    '^libxcb.*-dev' libx11-xcb-dev libgl1-mesa-dev libxrender-dev \
    libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libxtst-dev \
    && rm -rf /var/lib/apt/lists/*

# Make /vcpkg a volume
VOLUME /vcpkg

# Clone and bootstrap vcpkg if not already cloned
RUN if [ ! -d "$VCPKG_ROOT/.git" ]; then \
        git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT && \
        $VCPKG_ROOT/bootstrap-vcpkg.sh; \
    fi && \
    echo "export PATH=\"$VCPKG_ROOT:$PATH\"" >> /etc/profile

# Install pyenv and Python 3.9.18 to build the Exodus bundler
RUN curl https://pyenv.run | bash && \
    echo 'export PYENV_ROOT="/root/.pyenv"' >> /root/.bashrc && \
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> /root/.bashrc && \
    echo 'eval "$(pyenv init --path)"' >> /root/.bashrc && \
    echo 'eval "$(pyenv init -)"' >> /root/.bashrc && \
    /root/.pyenv/bin/pyenv install 3.9.18 && \
    /root/.pyenv/bin/pyenv global 3.9.18 && \
    /root/.pyenv/shims/pip install --upgrade pip setuptools wheel exodus-bundler jinja2 && \
    pip3 install jinja2

# Set the PATH for vcpkg
ENV PATH="$VCPKG_ROOT:$PATH"

# Define the default working directory
WORKDIR /workspace
