name: C/C++ CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build_ubuntu:
        name: C++ Build/Test on Ubuntu
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install deps
              run: scripts/ubuntu_deps.sh
            - name: Run CMake
              run: mkdir build && cd build && cmake -DBUILD_TESTING=ON ..
            - name: Build C++ lib/program and tests
              run: cd build && make -j$(nproc)
            - name: Test C++ lib/program
              run: cd build/test && ./test
            - name: Build Node.js bindings
              run: npm install
            - name: Test Node.js bindings
              run: npm test

    build_windows:
        name: C++ Build/Test on Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build C++ lib/program and tests
              run: |
                mkdir build
                cd build           
                cmake .. -DBUILD_TESTING=ON
                cmake --build . --config Debug --target ALL_BUILD -- /maxcpucount:14
                dir
            - name: Test C++ lib/program
              run: .\scripts\setup_windows_env.bat && cd build && test.exe
              shell: cmd