name: C/C++ CI

on:
    push:
        branches: [master]
        tags:
          - 'v*.*.*'
    pull_request:
        branches: [master]

jobs:
    build_ubuntu:
        name: Build/Test on Ubuntu
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: 'recursive'
            - name: Install deps
              run: scripts/ubuntu_deps.sh
            - name: Run CMake
              run: mkdir build && cd build && cmake -DBUILD_TESTING=ON ..
            - name: Build C++ lib/program and tests
              run: cd build && make -j$(nproc) test ddbcmd
            - name: Run C++ Tests
              run: cd build && ./test.run
            - name: Run Program Smoke Test
              run: cd build && ./ddb --debug
            - name: Build Distribution
              run: cd build && make -j$(nproc) dist
            - name: Upload Distribution Files
              uses: actions/upload-artifact@v2
              with:
                name: Compiled Binaries
                path: build/dist/*.tgz
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: build/dist/*.tgz
              env:
                GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    build_windows:
        name: Build/Test on Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: 'recursive'
            - name: Build C++ lib/program and tests
              run: |
                mkdir build
                cd build           
                cmake .. -DBUILD_TESTING=ON
                cmake --build . --config Release --target ALL_BUILD -- /maxcpucount:14
                dir
            - name: Run C++ Tests
              run: .\scripts\setup_windows_env.bat && cd build && test.exe
              shell: cmd
            - name: Run Program Smoke Test
              run: cd build && ddb.bat --debug
              shell: cmd
            - name: Create Distribution Files
              shell: cmd
              run: |
                cd build
                cmake --build . --config Release --target dist -- /maxcpucount:14
                dir
            - name: Upload Distribution Files
              uses: actions/upload-artifact@v2
              with:
                name: Compiled Binaries
                path: build\dist\*.zip
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: build\dist\*.zip
              env:
                GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}