name: Docs

on:
  push:
    branches: [ master ]

jobs:
  build-docs:
    runs-on: ubuntu-24.04
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-linux-release
      VCPKG_BUILD_TYPE: release
    steps:
    - name: Free Disk Space
      uses: ShubhamTatvamasi/free-disk-space-action@master
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-
    - name: Install Linux dependencies
      run: |
        chmod +x .github/scripts/install-dependencies.sh
        .github/scripts/install-dependencies.sh
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgJsonGlob: vcpkg.json
    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake -DVCPKG_OVERLAY_TRIPLETS=${{ github.workspace }}/vcpkg-triplets -DVCPKG_HOST_TRIPLET=x64-linux-release -DVCPKG_TARGET_TRIPLET=x64-linux-release -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ..
    - name: Build C++ lib/program
      run: cd build && make -j$(nproc)
    - name: Autogenerate command docs
      run: ./build/ddbcmd --gendocs --outdir docs/commands/
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.4
      with:
        build-command: "sphinx-build -b html . _build"
        docs-folder: "docs/"
    - name: Commit files
      run: |
        git clone https://github.com/DroneDB/docs.dronedb
        cp -r docs/_build/* docs.dronedb/
        cd docs.dronedb
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: "docs.dronedb"
        repository: "DroneDB/docs.dronedb"
        github_token: ${{ secrets.BOT_TOKEN }}
