name: .NET CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build_dotnet_windows:
      name: Build Windows .NET Bindings
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: 'recursive'
        - name: Build C++ lib
          run: |
            mkdir build
            cd build
            cmake .. -DBUILD_TESTING=OFF
            cmake --build . --config Release --target ddb -- /maxcpucount:14
            dir
        - name: Test .NET bindings
          run: |
            $env:PROJ_LIB = "$env:GITHUB_WORKSPACE\build"            
            dir build
            cd dotnet
            dotnet test -c Release
        - name: Publish .NET bindings
          run: |
            cd dotnet
            dotnet publish -c Release
            dir
        - name: Upload Library Files
          uses: actions/upload-artifact@v2
          with:
            name: .NET Bindings
            path: dotnet\DDB.Tests\bin\Release\netcoreapp3.1\*.*
    build_dotnet_linux:
      name: Build Linux .NET Bindings
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: 'recursive'
        - name: Install deps
          run: scripts/ubuntu_deps.sh
        - name: Run CMake
          run: mkdir build && cd build && cmake -DBUILD_TESTING=OFF ..
        - name: Build C++ lib
          run: cd build && make -j$(nproc) ddb && sudo make install && sudo ldconfig
        - name: Test .NET bindings
          run: |
            export PROJ_LIB=$GITHUB_WORKSPACE/build            
            ls $PROJ_LIB
            ls build
            cd dotnet            
            dotnet test -c Release         