name: NodeJS CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    ubuntu:
        name: Build/Test on Ubuntu
        runs-on: ubuntu-24.04
        env:
            VCPKG_ROOT: ${{ github.workspace }}/vcpkg
            VCPKG_DEFAULT_TRIPLET: x64-linux
            VCPKG_BUILD_TYPE: release
            CMAKE_JS_PLATFORM: linux
            CMAKE_JS_ARCH: x64
        steps:
            - name: Free Disk Space
              uses: ShubhamTatvamasi/free-disk-space-action@master
            - uses: actions/checkout@v4
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
            - name: Cache vcpkg
              uses: actions/cache@v4
              with:
                path: ${{ github.workspace }}/vcpkg
                key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
                restore-keys: |
                  ${{ runner.os }}-vcpkg-
            - name: Install Linux dependencies
              run: |
                chmod +x .github/scripts/install-dependencies.sh
                .github/scripts/install-dependencies.sh docs
            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11
              with:
                vcpkgDirectory: '${{ github.workspace }}/vcpkg'
                vcpkgJsonGlob: vcpkg.json
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'
                cache: 'npm'
            - name: Build Node.js bindings
              run: |
                npm install
            - name: Test Node.js bindings
              run: npm test

    windows:
        name: Build/Test on Windows
        runs-on: windows-latest
        env:
            VCPKG_ROOT: ${{ github.workspace }}/vcpkg
            VCPKG_DEFAULT_TRIPLET: x64-windows
            VCPKG_BUILD_TYPE: release
            CMAKE_JS_PLATFORM: win32
            CMAKE_JS_ARCH: x64
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: 'recursive'
            - name: Cache vcpkg
              uses: actions/cache@v4
              with:
                path: ${{ github.workspace }}/vcpkg
                key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
                restore-keys: |
                  ${{ runner.os }}-vcpkg-
            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11
              with:
                vcpkgDirectory: '${{ github.workspace }}/vcpkg'
                vcpkgJsonGlob: vcpkg.json
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'
            - name: Build Node.js bindings
              shell: pwsh
              run: |
                npm install
            - name: Test Node.js bindings
              shell: pwsh
              run: npm test
