name: NodeJS CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    ubuntu:
        name: Build/Test on Ubuntu
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
            - name: Install Linux dependencies
              run: |
                chmod +x .github/scripts/install-dependencies.sh
                .github/scripts/install-dependencies.sh docs
            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11
              with:
                vcpkgGitCommitId: acd65983f2e668c0bc44a117575e6073681fa8e3
                vcpkgDirectory: '${{ github.workspace }}/vcpkg'
                runVcpkgInstall: true
                doNotCache: false
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'
                cache: 'npm'
            - name: Build Node.js bindings
              run: |
                export CMAKE_JS_PLATFORM=linux
                export CMAKE_JS_ARCH=x64
                export VCPKG_ROOT=${GITHUB_WORKSPACE}/vcpkg
                npm install
            - name: Test Node.js bindings
              run: npm test

    windows:
        name: Build/Test on Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: 'recursive'
            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11
              with:
                vcpkgGitCommitId: acd65983f2e668c0bc44a117575e6073681fa8e3
                vcpkgDirectory: '${{ github.workspace }}/vcpkg'
                runVcpkgInstall: true
                doNotCache: false
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'
            - name: Build Node.js bindings
              shell: pwsh
              run: |
                $env:CMAKE_JS_PLATFORM = "win32"
                $env:CMAKE_JS_ARCH = "x64"
                $env:VCPKG_ROOT = "$env:GITHUB_WORKSPACE\vcpkg"
                npm install
            - name: Test Node.js bindings
              shell: pwsh
              run: npm test
