name: NodeJS CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    nodejs_ubuntu:
        name: NodeJS Build/Test on Ubuntu
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install deps
              run: scripts/ubuntu_deps.sh
            - name: Build Node.js bindings
              run: mkdir build && npm install
            - name: Test Node.js bindings
              run: npm test